#pragma once
enum OBJID { OBJ_BACKGROUND,  OBJ_ITEM_HEAL, OBJ_DEVILJELLY,OBJ_ITEM_BOOST, OBJ_ITEM_GIGA, OBJ_ITEM_GIGA2, OBJ_ITEM_MAGNET,OBJ_ITEM_SMALL, OBJ_DEVILCOIN, OBJ_PET, OBJ_MONSTE, OBJ_BULLET,OBJ_METEOR, OBJ_PLAYER, OBJ_END };

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_END };

enum SCENEID { SC_LOGO, SC_Robby, SC_STAGE, SC_SCORE, SC_END };

enum STATE { IDLE, WALK, JUMP, DOUBLEJUMP, SLIDE, DEAD, BOOST, GIGA, DEVIL, REVIVE, WITCH, STATE_END };

enum CHOICE { COFFEECOOKIE, DEVILCOOKIE, ZOMBIECOOKIE , WITCHC , CHOICE_END };

enum JELLY { BASE, NORMAL, RARE, JELLY_END };

enum CHANNELID { SOUND_EFFECT, SOUND_BGM, SOUND_PLAYER, SOUND_MONSTER, MAXCHANNEL };